version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3005:3005"
    volumes:
      - ./backend:/backend
    environment:
      - DATABASE_URL=mysql://root:@db:3306/SkyZeroDB
      - FLASK_APP=backend.app
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=3005
    depends_on:
      - db


frontend:
  build: ./react-frontend
  ports:
    - "85:85"
  environment:
    - PORT=85
    - REACT_APP_API_URL=http://backend:3005
  depends_on:
    - backend


  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: SkyZeroDB
    ports:
      - "3305:3306"
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data:
 